Roman_Numeral
Marwa-Sadat/Roman_Numeral pull request #1
Opened 2024-06-29 08:27 UTC by Marwa-Sadat

1. *Objective:* An app was created to convert numbers to Roman numerals and vice versa. ⚙🔢➡🏛
2. *Inputs:* Fields were provided for entering numbers and Roman numerals. ✏
3. *Conversion:* Logic was implemented to accurately handle both conversions. 🔄
4. *Validation:* Users were alerted for invalid inputs or formats. 🚫❗
5. *Styling:* A responsive and visually appealing user interface was designed. 🎨📱
6. *Deployment:* The app was hosted and ensured to be accessible online. 🌐
![Screenshot 2024-06-29 115526](https://github.com/Marwa-Sadat/Roman_Numeral/assets/168111110/90dc49e6-f19b-4c93-8fab-c1822c441425)

2024-07-01 18:56 UTC, zainabbehzad requested changes
Hi @Marwa-Sadat
Excellent work You have done a great job implementing the project requirements.

✔Great design implemented.
✔Created a professional Repo.
✔Correct use of Gitflow.
✔Commit messages are meaningful.
✔Setup the linters correctly.
✔No linters errors.
✔You have followed and completed the Palindrome Checker and all requirements.
✔Your codes passes all FreeCodeCamp requiremenrs.
✔Created the pull request (From your  Roman-Numeral branch to the development branch you created a pull request and submitted the pull request link for review).
✔Good PR description.
✔Your repo has a professional README.md.
✔Your project design is responsive.
🧩Your code is clean.
  On index.html
* Your body spacing is not aligned correctly:
* All child elements should be two spaces ahead of their parent elements.

In index.html you should not add CSS codes as you have external CSS file. And added this codes in your CSS file.
Also you should clear your comments when you finished your project (styles.css).

2024-07-04 12:30 UTC, Marwa-Sadat commented
Hi @zainabbehzad   I have done your feedback, please check my project .

2024-07-04 14:05 UTC, zainabbehzad approved these changes
Hi @Marwa-Sadat
Excellent work You have done a great job implementing the project requirements.

✔Great design implemented.
✔Created a professional Repo.
✔Correct use of Gitflow.
✔Commit messages are meaningful.
✔Setup the linters correctly.
✔No linters errors.
✔You have followed and completed the Palindrome Checker and all requirements.
✔Your codes passes all FreeCodeCamp requiremenrs.
✔Created the pull request (From your  Roman-Numeral branch to the development branch you created a pull request and submitted the pull request link for review).
✔Good PR description.
✔Your repo has a professional README.md.
✔Your project design is responsive.
✔Your code is clean.
  
Suggestion:
Just a little more work on your README.md

2024-07-04 14:05 UTC, zainabbehzad commented on index.html
> +      </style>
You should delete all these CSS codes from HTML file  instead link your CSS file in HTML file.
CSS link: <link rel="stylesheet" href="styles.css">

2024-07-04 14:11 UTC, Marwa-Sadat commented
Thank you
***@***.*** 😊 *

On Thu, Jul 4, 2024 at 07:05 Zainab Behzad ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @Marwa-Sadat <https://github.com/Marwa-Sadat>
> Excellent work You have done a great job implementing the project
> requirements.
>
> ✔Great design implemented.
> ✔Created a professional Repo.
> ✔Correct use of Gitflow.
> ✔Commit messages are meaningful.
> ✔Setup the linters correctly.
> ✔No linters errors.
> ✔You have followed and completed the Palindrome Checker and all
> requirements.
> ✔Your codes passes all FreeCodeCamp requiremenrs.
> ✔Created the pull request (From your Roman-Numeral branch to the
> development branch you created a pull request and submitted the pull
> request link for review).
> ✔Good PR description.
> ✔Your repo has a professional README.md.
> ✔Your project design is responsive.
> ✔Your code is clean.
>
> Suggestion:
> Just a little more work on your README.md
> ------------------------------
>
> In index.html
> <https://github.com/Marwa-Sadat/Roman_Numeral/pull/1#discussion_r1661472055>
> :
>
> > +         #convert-btn {
> +         padding: 10px 20px;
> +         border: none;
> +         background-color: #007BFF;
> +         color: white;
> +         border-radius: 4px;
> +         cursor: pointer;
> +         }
> +         #convert-btn:hover {
> +         background-color: #0056b3;
> +         }
> +         #output {
> +         margin-top: 20px;
> +         font-size: 18px;
> +         }
> +      </style>
>
> You should delete all these CSS codes from HTML file instead link your CSS
> file in HTML file.
> CSS link:
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Marwa-Sadat/Roman_Numeral/pull/1#pullrequestreview-2152136914>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BICSYBRN7GCVO2SVC45V3ATZKVJDFAVCNFSM6AAAAABKDAK6AKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNJSGEZTMOJRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-04 18:11 UTC, Marwa-Sadat commented
@ahzamir I hope you are well, I have done all the feedback, please check my project.

2024-07-05 14:23 UTC, ahzamir approved these changes
### Hi @Marwa-Sadat 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Marwa-Sadat/Roman_Numeral/assets/96838030/b052aa05-e474-494f-bd40-0c17b6477ec7)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-05 16:42 UTC, Marwa-Sadat commented
@ahzamir thank you so much sir 😊🙂.....

2024-07-08 07:01 UTC, merged